name: 'Check linter'
on:
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install package dependencies
        run: yarn install
      - name: Build project
        run: yarn workspaces run build:ci
      - name: Run lint
        run: yarn workspaces run lint:ci
        env:
          CI: true
          SKIP_PREFLIGHT_CHECK: true
