name: "Run all tests"
on:
- pull_request

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: Install Firebase Emulator
      run: npm i -g firebase-tools
    - name: Install package dependencies
      run: yarn install
    - name: Build project
      run: yarn workspaces run build:ci
    - name: Run tests
      run: yarn workspaces run test:ci
      env:
        CI: true
        SKIP_PREFLIGHT_CHECK: true